Rewrote outdated raw sql queries docs to match latest parameter binding update
serverpod/serverpod_docs pull request #110
Opened 2024-05-20 05:01 UTC by Aurangseb

This document was quite outdated and included functions that are not even there any more. Pretty much a rewrite from scratch.

2024-05-20 05:02 UTC, Aurangseb commented
Docs are related to: https://github.com/serverpod/serverpod/pull/2156

2024-05-20 11:14 UTC, Isakdl requested changes
Very nice! Thank you for the PR!

I have two small requested changes but other than that looking good! 👍

2024-05-20 11:14 UTC, Isakdl commented on docs/05-concepts/06-database/10-raw-access.md
> +Executes a single SQL query without returning any results. Use this for statements that modify data, such as `INSERT`, `UPDATE`, or `DELETE`. Returns the number of rows affected.
Suggestion: Change `without returning any results` as the method returns the number of effected rows.

2024-05-20 11:14 UTC, Isakdl commented on docs/05-concepts/06-database/10-raw-access.md
> +> Always sanitize your input when using raw query methods. For the `unsafeQuery` and `unsafeExecute` methods, use query parameters to prevent SQL injection. Avoid using `unsafeSimpleQuery` and `unsaf
Suggestion:

Keep the
```md
:::danger
content
:::
```

As it renders a nice visual box

<img width="979" alt="Screenshot 2024-05-20 at 13 12 22" src="https://github.com/serverpod/serverpod_docs/assets/7395515/4eeb9887-e24f-41df-a3de-1db6d027ad29">

2024-05-29 13:07 UTC, Isakdl approved these changes
LGTM

2024-05-29 13:08 UTC, merged