Authentication improvements
serverpod/serverpod_docs pull request #13
Opened 2023-05-29 13:59 UTC by Isakdl

# Changes
- Restructure the authentication documentation into several pages.
- Restructures each provider in the auth module into their own pages.
- Expand each provider with more detailed instructions for the setup.

# Closes
https://github.com/serverpod/serverpod/issues/843
https://github.com/serverpod/serverpod/issues/857
https://github.com/serverpod/serverpod/issues/544

# Todo
https://github.com/serverpod/serverpod/issues/350

2023-05-29 20:19 UTC, easazade commented
@Isakdl I like a detailed documentation. 👍

2023-06-02 09:06 UTC, vlidholt requested changes
Great! Found some minor things. :)

2023-06-02 09:06 UTC, vlidholt commented on docs/04-concepts/09-authentication/03-providers/02-google.md
> +1. Fill in all the required information, for production use you need a domain that adds under `Authorized` domains`.
The trailing quote can mess up the formatting here.

2023-06-02 09:06 UTC, vlidholt commented on docs/04-concepts/09-authentication/03-providers/03-apple.md
> +A comprehensive tutorial covering Sign in with Apple is available [here](#todo).
Let's upload it :)

2023-06-02 09:06 UTC, vlidholt commented on docs/04-concepts/09-authentication/03-providers/03-apple.md
> +Right now, we only have official support for iOS and MacOS for Sign in with Apple.
Remove only. :P

2023-06-02 13:36 UTC, Isakdl commented on docs/04-concepts/09-authentication/03-providers/01-email.md
> +For debugging purposes, you can print the validation code to the console. The chat module example does just this. You can view that code [here](https://github.com/serverpod/serverpod/blob/main/exampl
Yes, the chat module still does this!

2023-06-02 13:44 UTC, Isakdl commented on docs/04-concepts/09-authentication/01-the-basics.md
> +  static const readUsers = CustomScope('read:users');
Not following what you mean, Scopes are just strings right or do we parse them in some special way?

Using `:` is quite common in scopes.

For example, slack:
https://api.slack.com/scopes

Could also be modeled with a `.` but the order should probably be reversed though. `resource:access_type` or `resource.access_type` I.E. `user.read`

2023-06-02 14:00 UTC, Isakdl commented
@vlidholt check the update! :)

2023-06-03 03:35 UTC, braj065 commented
Will the changes in documentation contain details on how to authenticate(google api, firebase etc) using serverpod api calls directly and not using the pre-made serverpod auth widgets? And try to keep the serverpod auth api use in the docs higher/more preferred than the premade auth widgets.

2023-06-04 21:09 UTC, andriyndev commented
It looks like info about error handling is missing.

2023-06-25 20:22 UTC, merged