add explanation of .spy.yaml to "Working with models"
serverpod/serverpod_docs pull request #85
Opened 2024-03-27 09:59 UTC by BenAuerDev

Good morning @SandPod , 

As I was already looking into this, I figured I'd try and add it to the documentation :) 

let me know if something needs to be changed 

Ben

2024-03-27 10:07 UTC, Isakdl requested changes
Thank you for the PR :)!

I have requested one change for an invalid description. 

A minor addition that could be useful but not necessary is to add that if the .spy.yaml extension is used you get syntax highlighting with the Serverpod VSCode plugin.

2024-03-27 10:07 UTC, Isakdl commented on docs/05-concepts/02-models.md
> +Models are Yaml files used to define serializable classes in Serverpod. They are used to generate Dart code for the server and client, and, if a database table is defined, to generate database code f
> and when defining a model elsewhere within `lib/src`

Suggestion: Remove this part as this is currently not a supported use-case. If you define the models elsewhere the code generator will not pick up the files.

2024-03-27 10:41 UTC, BenAuerDev commented
@Isakdl thanks for the quick feedback :) 

I removed the invalid description and added info about the VS Code Extension with a link to the marketplace. 

Let me know when it needs more tweaking :+1:

2024-03-28 09:47 UTC, BenAuerDev commented
also done :)

2024-03-28 10:05 UTC, Isakdl approved these changes
LGTM

2024-03-28 10:06 UTC, merged